global:
  resolve_timeout: 5m

route:
  receiver: 'default-receiver'
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'your@email.com'
        from: 'alertmanager@email.com'
        smarthost: 'smtp.example.com:587'
        auth_username: 'alertmanager@email.com'
        auth_password: 'yourpassword'
        require_tls: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance'] 